# -*- coding: utf-8 -*-
"""Time_Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tm4qefXGnCsBYT811fAhb-hZVtpM-I8b
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('/content/monthly_milk_production.csv',index_col='Date',parse_dates=True)
df.index.freq='MS'

df.head()

df.plot(figsize=(12,6))

from statsmodels.tsa.seasonal import seasonal_decompose

results=seasonal_decompose(df['Production'])
results.plot();

len(df)

train=df.iloc[:156]
test=df.iloc[156:]

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

df.head(),df.tail()

scaler.fit(train)
scaled_train=scaler.transform(train)
scaled_test=scaler.transform(test)

scaled_train[:10]

from keras.preprocessing.sequence import TimeseriesGenerator

n_input=12
n_features=1
generator=TimeseriesGenerator(scaled_train,scaled_train,length=n_input,batch_size=1)

X,y=generator[0]
print(f'Given the Array: \n{X.flatten()}')
print(f'Predict this y: \n {y}')

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

model=Sequential()
model.add(LSTM(100,activation='relu',input_shape=(n_input,n_features)))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')

model.summary()

model.fit(generator,epochs=50)

loss_per_epoch=model.history.history['loss']
plt.plot(range(len(loss_per_epoch)),loss_per_epoch)

last_train_batch=scaled_train[-12:]

last_train_batch=last_train_batch.reshape((1,n_input,n_features))

model.predict(last_train_batch)

scaled_test[0]

test_predictions=[]

first_eval_batch=scaled_train[-n_input:]
current_batch=first_eval_batch.reshape(1,n_input,n_features)

for i in range(len(test)):
  current_pred=model.predict(current_batch)[0]
  test_predictions.append(current_pred)
  current_batch=np.append(current_batch[:,1:,:],[[current_pred]],axis=1)

test_predictions

true_predictions=scaler.inverse_transform(test_predictions)

test['Predictons']=true_predictions

test.plot(figsize=(12,6))

test.head()

from sklearn.metrics import mean_squared_error
from math import sqrt
rmse=sqrt(mean_squared_error(test['Production'],test['Predictons']))
print(rmse)

